<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseTree extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('tree');
    $this->hasColumn('name', 'string', 255, array('type' => 'string', 'length' => '255'));
  }

  public function setUp()
  {
    $nestedset0 = new Doctrine_Template_NestedSet(array('hasManyRoots' => true, 'rootColumnName' => 'root_id'));
    $this->actAs($nestedset0);
  }
}